Python/Django/refugio/adopcion/urls.py
from django.urls import path
from adopcion.views import index, SolicitudListView, SolicitudCreateView

app_name = 'adopcion'

urlpatterns = [
    path('', index),
    path('listar', SolicitudListView.as_view(), name="solicitud_listar"),
    path('crear', SolicitudCreateView.as_view(), name="solicitud_crear"),
    
]

Python/Django/refugio/mascota/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from mascota.views import listado, index, mascota_view, mascota_list, mascota_edit, mascota_delete, MascotaListView, MascotaCreateView, MascotaUpdateView, MascotaDeleteView

app_name = 'mascota'

urlpatterns = [
    path('', index, name="index"),
    #path('crear', mascota_view, name="mascota_crear"),
    #path('listar', mascota_list, name="mascota_listar"),
    #path('editar/<int:id_mascota>/', mascota_edit, name="mascota_editar"),
    #path('eliminar/<int:id_mascota>/', mascota_delete, name="mascota_eliminar"),
    #con Clases
    path('crear', login_required(MascotaCreateView.as_view()), name="mascota_crear"),
    path('listar', login_required(MascotaListView.as_view()), name="mascota_listar"),
    path('editar/<int:pk>/', login_required(MascotaUpdateView.as_view()), name="mascota_editar"),
    path('eliminar/<int:pk>/', login_required(MascotaDeleteView.as_view()), name="mascota_eliminar"),

    path('listado', listado, name="listado"),
]

Python/Django/refugio/refugio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
urlpatterns = [
    path('', LoginView.as_view(template_name='usuario/login.html'), name="login"),
    path('admin/', admin.site.urls),
    path('mascota/', include("mascota.urls")),
    path('adopcion/', include("adopcion.urls")),
    path('usuario/', include("usuario.urls")),
    path('accounts/login/', LoginView.as_view(template_name='usuario/login.html'), name="login"),
    path('logout/', logout_then_login, name="logout"),
    path('reset/password_reset/', PasswordResetView.as_view(template_name='registration/password_reset_form.html',email_template_name='registration/password_reset_email.html'),  name="password_reset"),
    path('reset/password_reset_done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name="password_reset_confirm"),
    path('reset/complete/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name="password_reset_complete"),
]

Python/Django/refugio/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    {% block extrastatic %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Document {% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block navbar %}
            <div class="bs-docs-section clearfix">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bs-component">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <div class="navbar-header">
                                <a class="navbar-brand" href="#">Home</a>
                                </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'mascota:mascota_crear'%}">Registrar</a></li>
                                    <li><a href="{% url 'mascota:mascota_listar'%}">Listar</a></li>
                                    </ul>
                                    </li>
                                    <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Adopciones<span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{% url 'adopcion:solicitud_crear'%}">Solicitar</a></li>
                                        <li><a href="{% url 'adopcion:solicitud_listar'%}">Listar solicitudes</a></li>
                                    </ul>
                                    </li>
                                </ul>
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{% url 'logout' %}">Salir</a></li>
                                    </ul>
                                    </li>
                                </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                    </div>
                </div>
            </div>
        {% endblock %}
        {% block content %}
        {% endblock %}
        {% block footer %}
        {% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>