Python/Django/refugio/mascota/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from mascota.views import listado, index, mascota_view, mascota_list, mascota_edit, mascota_delete, MascotaListView, MascotaCreateView, MascotaUpdateView, MascotaDeleteView

app_name = 'mascota'

urlpatterns = [
    path('', index, name="index"),
    #path('crear', mascota_view, name="mascota_crear"),
    #path('listar', mascota_list, name="mascota_listar"),
    #path('editar/<int:id_mascota>/', mascota_edit, name="mascota_editar"),
    #path('eliminar/<int:id_mascota>/', mascota_delete, name="mascota_eliminar"),
    #con Clases
    path('crear', login_required(MascotaCreateView.as_view()), name="mascota_crear"),
    path('listar', login_required(MascotaListView.as_view()), name="mascota_listar"),
    path('editar/<int:pk>/', login_required(MascotaUpdateView.as_view()), name="mascota_editar"),
    path('eliminar/<int:pk>/', login_required(MascotaDeleteView.as_view()), name="mascota_eliminar"),

    path('listado', listado, name="listado"),
]

Python/Django/refugio/refugio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
urlpatterns = [
    path('', LoginView.as_view(template_name='usuario/login.html'), name="login"),
    path('admin/', admin.site.urls),
    path('mascota/', include("mascota.urls")),
    path('adopcion/', include("adopcion.urls")),
    path('usuario/', include("usuario.urls")),
    path('accounts/login/', LoginView.as_view(template_name='usuario/login.html'), name="login"),
    path('logout/', logout_then_login, name="logout"),
    path('reset/password_reset/', PasswordResetView.as_view(template_name='registration/password_reset_form.html',email_template_name='registration/password_reset_email.html'),  name="password_reset"),
    path('reset/password_reset_done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name="password_reset_confirm"),
    path('reset/complete/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name="password_reset_complete"),
]

Python/Django/refugio/mascota/models.py
from django.db import models
# Create your models here.
from adopcion.models import Persona
class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return "{}".format(self.nombre)

class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

Python/Django/refugio/mascota/forms.py
from django import forms
from mascota.models import Mascota
class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota

        fields = [  "nombre",
                    "sexo",
                    "edad_aproximada",
                    "fecha_rescate",
                    "persona",
                    "vacuna"]

        labels = {  "nombre":"Nombre", 
                    "sexo":"Sexo",
                    "edad_aproximada":"Edad Aproximada",
                    "fecha_rescate":"Fecha De Rescate",
                    "persona":"Persona",
                    "vacuna":"Vacuna"}

        widgets = { "nombre": forms.TextInput(attrs={"class":"form-control"}),
                    "sexo": forms.TextInput(attrs={"class":"form-control"}),
                    "edad_aproximada": forms.TextInput(attrs={"class":"form-control"}),
                    "fecha_rescate": forms.TextInput(attrs={"class":"form-control"}),
                    "persona": forms.Select(attrs={"class":"form-control"}),
                    "vacuna": forms.CheckboxSelectMultiple()}
                    

Python/Django/refugio/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
from mascota.forms import MascotaForm
from mascota.models import Mascota
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# Create your views here.
def listado(request):
    lista = serializers.serialize("json", Mascota.objects.all(), fields=["nombre","sexo"])
    return HttpResponse(lista)

def index(request):
    return render(request, "mascota/index.html")

def mascota_view(request):
    if request.method == "POST":
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("mascota:index")
    else:
        form = MascotaForm()

    return render(request, "mascota/mascota_form.html", {"form":form})

def mascota_list(request):
    mascota = Mascota.objects.all()
    contexto = {"mascotas":mascota}
    return render(request, "mascota/mascota_list.html", contexto)

def mascota_edit(request,id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == "GET":
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect("mascota:mascota_listar")
    return render(request,"mascota/mascota_form.html",{"form":form})

def mascota_delete(request,id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == "POST":
        mascota.delete()
        return redirect("mascota:mascota_listar")
    return render(request,"mascota/mascota_delete.html",{"mascota":mascota})

#vistas como clases
class MascotaListView(ListView):
    model = Mascota
    template_name = "mascota/mascota_list_2.html"

class MascotaCreateView(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = "mascota/mascota_form.html"
    success_url = reverse_lazy("mascota:mascota_listar_2")

class MascotaUpdateView(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = "mascota/mascota_form.html"
    success_url = reverse_lazy("mascota:mascota_listar_2")

class MascotaDeleteView(DeleteView):
    model = Mascota
    template_name = "mascota/mascota_delete.html"
    success_url = reverse_lazy("mascota:mascota_listar_2")

Python/Django/refugio/templates/mascota/index.html
{% extends "base/base.html" %}
{% block title %}
    APP MASCOTA
{% endblock %}
{% block content %}
<h4> este es el contenido de mascota</h4>
{% endblock %}

Python/Django/refugio/templates/mascota/mascota_delete.html
{% extends "base/base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>Desea eliminar el registro de {{mascota.nombre}}</h3>
    <button class="btn btn-danger" type="submit">Si, Eliminar</button>
    <a class="btn btn-default" href="{% url 'mascota:mascota_listar'%}">Volver al listado</a>
</form>
{% endblock %}

Python/Django/refugio/templates/mascota/mascota_form.html
{% extends "base/base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

Python/Django/refugio/templates/mascota/mascota_list.html
{% extends "base/base.html" %}

{% block content %}
{% if mascotas %}
    <table class="table table-bordered">
        <thead>
            <td>#</td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Edad</td>
            <td>Fecha de Rescate</td>
            <td>Adoptante</td>
            <td>Acciones</td>
        </thead>
        <tbody>
            {% for mascota in mascotas%}
                <tr>
                    <td>{{mascota.id}}</td>
                    <td>{{mascota.nombre}}</td>
                    <td>{{mascota.sexo}}</td>
                    <td>{{mascota.edad_aproximada}}</td>
                    <td>{{mascota.fecha_rescate}}</td>
                    <td>{{mascota.persona.nombre}} {{mascota.persona.apellidos}}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor%}
        </tbody>
    </table>
{% else %}
    <p> No hay registro de Mascotas</p>
{% endif %}        

{% endblock %}

Python/Django/refugio/templates/mascota/mascota_list_2.html
{% extends "base/base.html" %}

{% block content %}
{% if object_list %}
    <table class="table table-bordered">
        <thead>
            <td>#</td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Edad</td>
            <td>Fecha de Rescate</td>
            <td>Adoptante</td>
            <td>Acciones</td>
        </thead>
        <tbody>
            {% for mascota in object_list%}
                <tr>
                    <td>{{mascota.id}}</td>
                    <td>{{mascota.nombre}}</td>
                    <td>{{mascota.sexo}}</td>
                    <td>{{mascota.edad_aproximada}}</td>
                    <td>{{mascota.fecha_rescate}}</td>
                    <td>{{mascota.persona.nombre}} {{mascota.persona.apellidos}}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor%}
        </tbody>
    </table>
{% else %}
    <p> No hay registro de Mascotas</p>
{% endif %}        

{% endblock %}